# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!

# Pods for all Targets
def shared_pods
    pod 'Alamofire'
    pod 'SDWebImage', '~> 5.11'
    pod 'UIColor_Hex_Swift', '~> 5.1.7'
end

target 'LuckyApp' do
    shared_pods
end

target 'LuckyAppTests' do
    shared_pods
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        end
    end
end